#!/usr/bin/env ruby

require 'kikori'
require 'thor'
require 'pry'

module Kikori
  # Use on CLI
  class CLI < Thor
    class_option :help, type: :boolean, aliases: '-h', desc: 'help message.'
    class_option :version, type: :boolean, desc: 'version'
    default_task :hello

    desc 'find', '横断検索だ！'
    def find(query, cmd = nil)
      tree = Kikori.find(query)
      case cmd
      when '-b'
        puts tree.branch_names
      when '-f'
        puts tree.paths
      when nil
        puts tree.leafs
      end

      tree.branches.map(&:leaf)
    end

    desc 'version', 'show version'
    def version
      puts Kikori::VERSION
    end
  end
end

Kikori::CLI.start(ARGV)
