#!/usr/bin/env ruby

require 'kikori'
require 'thor'
require 'pry'

module Kikori
  class CLI < Thor
    class_option :help, type: :boolean, aliases: '-h', desc: 'help message.'
    class_option :version, type: :boolean, desc: 'version'
    default_task :hello

    desc 'hello', 'say hello world!'
    def hello
      puts 'hello'
    end

    desc 'version', 'show version'
    def version
      puts Kikori::VERSION
    end

    desc 'pry', 'pry!'
    def pry
      binding.pry
    end
  end
end

Kikori::CLI.start(ARGV)
